### ISSUE TITLE
Abstract suggestions

### ISSUE THREAD

**Issue by daniel-s-ingram** [AtsushiSakai/PythonRoboticsPaper#3]
Open Source Software -> Open-Source Software

This is a Python code collection of robotics algorithms -> This is a collection of robotics algorithms implemented in the Python programming language.

The focus… -> The focus of the project is on autonomous navigation, and the goal is for beginners in robotics to understand the basic ideas behind each algorithm.

Each sample code… -> Each algorithm is written in Python3 and depends only on common modules, such as NumPy and Matplotlib, for readability, portability and ease of use.

I will make some suggestions on the rest of the paper some time over the next few days.

**Comment by AtsushiSakai** [comment]
@daniel-s-ingram Thank you for your review!! I fix the paper based on your suggestion.
